Adds capability to sample variables at the location of a ray
idaholab/fenix pull request #15
Opened 2024-01-23 22:44 UTC by gsgall

Closes #12

2024-01-23 22:51 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2022500/) on c32daa0 wanted to post the following:

View the site [here](https://fenix-dev.hpc.inl.gov/PRs/15/site)

This comment will be updated on new commits.

2024-01-23 22:52 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2022504/) on c32daa0 wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>783e89</th>
      <th colspan=4>#15 c32daa</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>89.92%</td>
      <td>90.51%</td>
      <td>+0.59%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>116</td>
      <td>124</td>
      <td>+8</td>
      <td>8</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>13</td>
      <td>13</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://fenix-dev.hpc.inl.gov/PRs/15/coverage_diff)

[Full coverage report](https://fenix-dev.hpc.inl.gov/PRs/15/coverage)



This comment will be updated on new commits.

2024-01-24 19:48 UTC, cticenhour requested changes
Beyond these noted comments, please also change the title of the PR to be more reflective of the PR content and change the commit message to reflect the content (having `closes #12` at the end of the commit is still OK - we just need a descriptive commit message).

2024-01-24 19:48 UTC, cticenhour commented on doc/content/source/utils/VariableSampler.md
> +The sampler is designed to be used with rays. The point parameter exist within the provided element parameter. After instantiation, use `VariableSampler::sampleVariable()` to sample the value of a va
```suggestion
The sampler is designed to be used with rays. The point parameter exists within the provided element parameter. After instantiation, use `VariableSampler::sampleVariable()` to sample the value of a variable at a point in space.
```

2024-01-24 19:48 UTC, cticenhour commented on include/utils/VariableSampler.h
> + * Utility that samples the value of a vector variable at a given point
You mention vector variables explicitly here, but not in the documentation markdown. Is this for all variables or only vectors? Depending on which it is, the markdown or this line should be updated to reflect that.

2024-01-24 19:48 UTC, cticenhour commented on include/utils/VariableSampler.h
> +   * @param point the point where you want to know the value of a variable
```suggestion
   * @param point the point at which you want to know the value of a variable
```

2024-01-24 19:48 UTC, cticenhour commented on include/utils/VariableSampler.h
> +  /// the variable number for the vector field in the system
```suggestion
  /// The variable number for the vector field in the system
```

2024-01-24 19:48 UTC, cticenhour commented on test/include/userobjects/TestVariableSampler.h
> +class TestVariableSampler : public TestPICStudyUserDefinedRays
```suggestion
#include "TestPICStudyUserDefinedRays.h"

class TestVariableSampler : public TestPICStudyUserDefinedRays
```

2024-01-24 19:48 UTC, cticenhour commented on test/include/userobjects/TestVariableSampler.h
> +  /// the ray data index where the value of sampled field will be stored
```suggestion
  /// The utility used to sample a moose variable as a ray is traveling
  const FENIX::VariableSampler _sampler;
  /// The ray data index where the value of sampled field will be stored
```

2024-01-24 19:48 UTC, cticenhour commented on test/tests/utils/variable_sampler/tests
> +    requirement = 'A ray should be able to sample the value of field variable at any point in space as it moves through space'
```suggestion
    requirement = 'The system shall allow a ray to sample the value of field variable at any point in space as it moves through space'
```

2024-01-24 19:55 UTC, gsgall commented on include/utils/VariableSampler.h
> + * Utility that samples the value of a vector variable at a given point
That is left over from the original one where I was trying to sample vectors but from our discussions in slack this does not work for vector variables. I have updated this comment to reflect the real ability of this utility.

2024-01-25 20:10 UTC, cticenhour approved these changes

2024-01-25 20:10 UTC, merged