Add ResidualAccumulator
idaholab/fenix pull request #17
Opened 2024-02-25 21:41 UTC by loganharbour

Closes #16

2024-02-25 21:48 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2084912/) on 9ba0d64 wanted to post the following:

View the site [here](https://fenix-dev.hpc.inl.gov/PRs/17/site)

This comment will be updated on new commits.

2024-02-25 21:49 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2084916/) on 9ba0d64 wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>ce2b14</th>
      <th colspan=4>#17 9ba0d6</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>90.91%</td>
      <td>91.53%</td>
      <td>+0.62%</td>
      <td>96.30%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>130</td>
      <td>162</td>
      <td>+32</td>
      <td>52</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>13</td>
      <td>15</td>
      <td>+2</td>
      <td>2</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://fenix-dev.hpc.inl.gov/PRs/17/coverage_diff)

[Full coverage report](https://fenix-dev.hpc.inl.gov/PRs/17/coverage)



This comment will be updated on new commits.

2024-02-27 01:29 UTC, gsgall requested changes

2024-02-27 01:29 UTC, gsgall commented on doc/content/source/utils/ResidualAccumulator.md
> +instantiate an `ResidualAccumulator` when you want to contribute to the field, and then
```suggestion
instantiate a `ResidualAccumulator` when you want to contribute to the field, and then
```

2024-02-27 01:29 UTC, gsgall commented on doc/content/source/utils/ResidualAccumulator.md
> +to the field. The finalization will take care of properly closing the aux variable.
Doe the residual accumulator operate only on aux variables. I thought this required a nonLinearVariable to work properly.

2024-02-27 01:29 UTC, gsgall commented on include/utils/ResidualAccumulator.h
> +  const MooseVariableField<Real> & _var;
Is this comment accurate? I didn't think that the residual accumulator required a RayKernel.

2024-02-27 23:25 UTC, cticenhour requested changes
Noticed one small thing. Requesting changes until @gsgall's comments are addressed.

2024-02-27 23:25 UTC, cticenhour commented on include/utils/AccumulatorBase.h
> + * Base class for a uility that accumulates point values into a variable
```suggestion
 * Base class for a utility that accumulates point values into a variable
```

2024-02-28 19:25 UTC, loganharbour commented
Should be good to go now.

2024-02-28 19:26 UTC, gsgall approved these changes
Looks good to me thank you Logan!

2024-02-29 17:56 UTC, cticenhour approved these changes

2024-02-29 17:57 UTC, merged

2024-03-04 15:59 UTC, cticenhour commented
@loganharbour Unfortunately, this isn't Valgrind clean: https://civet.inl.gov/job/2087206/

I may be able to take a peek today.

2024-03-05 17:36 UTC, loganharbour commented
> @loganharbour Unfortunately, this isn't Valgrind clean: https://civet.inl.gov/job/2087206/
> 
> I may be able to take a peek today.

Resolved in https://github.com/idaholab/fenix/pull/18