Closes #25 Adding the ability to solve for the electrostatic potential based on particle positions
idaholab/fenix pull request #26
Opened 2024-04-02 02:28 UTC by gsgall

Closes #25

2024-04-02 02:37 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2166426/) on 57a79d3 wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>f290db</th>
      <th colspan=4>#26 57a79d</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>91.87%</td>
      <td>92.39%</td>
      <td>+0.52%</td>
      <td>96.77%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>226</td>
      <td>255</td>
      <td>+29</td>
      <td>30</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>20</td>
      <td>21</td>
      <td>+1</td>
      <td>1</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://fenix-dev.hpc.inl.gov/PRs/26/coverage_diff)

[Full coverage report](https://fenix-dev.hpc.inl.gov/PRs/26/coverage)



This comment will be updated on new commits.

2024-04-02 02:37 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2166422/) on 57a79d3 wanted to post the following:

View the site [here](https://fenix-dev.hpc.inl.gov/PRs/26/site)

This comment will be updated on new commits.

2024-04-02 04:14 UTC, simopier commented
@gsgall 
The issue number should appear in the PR description rather than the PR title (which does not create a link). 

I added it in the description. Don't worry about removing it from the title right now, but please keep that in mind for next time. Thanks!

2024-04-02 04:20 UTC, gsgall commented
> @gsgall The issue number should appear in the PR description rather than the PR title (which does not create a link).
> 
> I added it in the description. Don't worry about removing it from the title right now, but please keep that in mind for next time. Thanks!

Than you! @simopier

2024-04-02 04:54 UTC, simopier requested changes
Looks good, thanks for this contribution! 
I have a few comments and a couple of questions, including:
- Please reference your PBNC paper and explicitly link the verification case from the paper to the appropriate tests (with links such as [charge_accumulator2D.i]).
- Could you help me understand why the result from [charge_accumulator2D_out.e](https://github.com/idaholab/fenix/pull/26/files#diff-9bfa4cba94614ef2f042b62b0d42c805ba555b1b3d0cba2f9a5380177be31148) looks like the figure below (F being plotted here) instead of having more symmetry? I don't understand why the top-right and bottom left corners are not like the top-left and bottom-right ones. 
<img width="515" alt="Screenshot 2024-04-01 at 10 48 50 PM" src="https://github.com/idaholab/fenix/assets/17445651/4f634532-2f26-44fa-998c-300daf732443">

2024-04-02 04:54 UTC, simopier commented on doc/content/source/userobjects/ChargeAccumulator.md
> +  \right)
```suggestion
  \right),
```

2024-04-02 04:54 UTC, simopier commented on doc/content/source/userobjects/ChargeAccumulator.md
> +Where $N$ is the number of computational particles in the simulation, $q_i$ is the charge of the $i^\text{th}$ particle, and $\vec{r}_i$ is the position at which the ith computational particle exists
```suggestion
where $N$ is the number of computational particles in the simulation, $q_i$ is the charge of the $i^\text{th}$ particle, and $\vec{r}_i$ is the position at which the $i^\text{th}$ computational particle exists.
```

2024-04-02 04:54 UTC, simopier commented on doc/content/source/userobjects/ChargeAccumulator.md
> +In FENIX the charge density is defined as
```suggestion
In FENIX the charge density $\rho$ is defined as
```

2024-04-02 04:54 UTC, simopier commented on doc/content/source/userobjects/ChargeAccumulator.md
> +  0
```suggestion
  0.
```

2024-04-02 04:54 UTC, simopier commented on doc/content/source/userobjects/ChargeAccumulator.md
> +The second term of the weak form of Poisson's equation can then be evaulated as
```suggestion
The second term of the weak form of Poisson's equation can then be evaluated as
```

2024-04-02 04:54 UTC, simopier commented on doc/content/source/userobjects/ChargeAccumulator.md
> +  \right)
```suggestion
  \right),
```

2024-04-02 04:54 UTC, simopier commented on doc/content/source/userobjects/ChargeAccumulator.md
> +Where $M$ is the number of particles which exist on the subdomain where the $j^\text{th}$ test function $\psi_j$ is non-zero. This objects evaluates this source term directly and accumulates the resu
```suggestion
where $M$ is the number of particles which exist on the subdomain where the $j^\text{th}$ test function $\psi_j$ is non-zero. This objects evaluates this source term directly and accumulates the result directly into the residual of the variable representing $\phi$.
```

2024-04-02 04:54 UTC, simopier commented on doc/content/source/userobjects/ChargeAccumulator.md
> +This object should be set to execute on `PRE_KERNELS` so that the residual contribution from the charge density source term is computed correctly
```suggestion
This object should be set to execute on `PRE_KERNELS` so that the residual contribution from the charge density source term is computed correctly.
```

2024-04-02 04:54 UTC, simopier commented on doc/content/source/userobjects/ChargeAccumulator.md
> +This object should be set to execute on `PRE_KERNELS` so that the residual contribution from the charge density source term is computed correctly
Thank you for being thorough and transparent with the documentation!

2024-04-02 04:54 UTC, simopier commented on doc/content/source/userobjects/ChargeAccumulator.md
> +\begin{equation}
```suggestion
\begin{equation} \label{eq:weak_poisson_right_term}
```

2024-04-02 04:54 UTC, simopier commented on doc/content/source/userobjects/ChargeAccumulator.md
> +\begin{equation}
```suggestion
\begin{equation} \label{eq:charge_density}
```

2024-04-02 04:54 UTC, simopier commented on doc/content/source/userobjects/ChargeAccumulator.md
> +\begin{equation}
```suggestion
\begin{equation} \label{eq:poisson}
```

2024-04-02 04:54 UTC, simopier commented on doc/content/source/userobjects/ChargeAccumulator.md
> +\begin{equation}
This ensures that equations have numbers.

2024-04-02 04:54 UTC, simopier commented on include/userobjects/ChargeAccumulator.h
> +   * this is computing the inner product of the point source charge density
```suggestion
   * the particles to the residuals of a finite element variable.
   * This is computing the inner product of the point source charge density
```

2024-04-02 04:54 UTC, simopier commented on include/userobjects/ChargeAccumulator.h
> +   * the execute method will get all of the particles that are being tracked
```suggestion
   * The execute method will get all of the particles that are being tracked
```

2024-04-02 04:54 UTC, simopier commented on src/userobjects/ChargeAccumulator.C
> +  // Make sure that you add these params when using the ResidualAccumulator
Honest question: Are those comments you had for yourself during development, or do you want to leave them in the code?

2024-04-02 04:54 UTC, simopier commented on src/userobjects/ChargeAccumulator.C
> +  // You need to add this exec flag so it can contribute to residuals
Honest question: Are those comments you had for yourself during development, or do you want to leave them in the code?

2024-04-02 04:54 UTC, simopier commented on src/userobjects/ChargeAccumulator.C
> +    // the nonlinear system is not strictly always 0 but this is good enough for now
Could you expand on when that would not be enough anymore?

2024-04-02 04:54 UTC, simopier commented on test/tests/userobjects/charge_accumulation/simple_potential_solve.i
> +
```suggestion
```

2024-04-02 04:54 UTC, simopier commented on test/tests/userobjects/charge_accumulation/simple_potential_solve.i
> +
```suggestion
```

2024-04-02 04:54 UTC, simopier commented on test/tests/utils/auxaccumulator/tests
> +    requirement = 'The system shall support mapping data from rays to an aux variable and reset the aux variable to 0 on each time step on a 2 dimenstional mesh'
```suggestion
    requirement = 'The system shall support mapping data from rays to an aux variable and reset the aux variable to 0 on each time step on a 2 dimensional mesh'
```

2024-04-02 12:51 UTC, gsgall commented on src/userobjects/ChargeAccumulator.C
> +    // the nonlinear system is not strictly always 0 but this is good enough for now
I just double checked my discussion with @loganharbour and he said for what we're doing it should always be zero so I will remove this comment

2024-04-02 12:53 UTC, gsgall commented on src/userobjects/ChargeAccumulator.C
> +  // You need to add this exec flag so it can contribute to residuals
This was some copy pasta left over from the residual accumulator test object. I can go either way, keeping them or removing them. If you have a preference we can do that.

2024-04-02 12:54 UTC, gsgall commented on src/userobjects/ChargeAccumulator.C
> +  // Make sure that you add these params when using the ResidualAccumulator
See my response to the same comment on the same object.

2024-04-02 12:59 UTC, gsgall commented
> Looks good, thanks for this contribution! I have a few comments and a couple of questions, including:
> 
> * Please reference your PBNC paper and explicitly link the verification case from the paper to the appropriate tests (with links such as [charge_accumulator2D.i]).
> * Could you help me understand why the result from [charge_accumulator2D_out.e](https://github.com/idaholab/fenix/pull/26/files#diff-9bfa4cba94614ef2f042b62b0d42c805ba555b1b3d0cba2f9a5380177be31148) looks like the figure below (F being plotted here) instead of having more symmetry? I don't understand why the top-right and bottom left corners are not like the top-left and bottom-right ones.
> 
> <img alt="Screenshot 2024-04-01 at 10 48 50 PM" width="515" src="https://private-user-images.githubusercontent.com/17445651/318646404-4f634532-2f26-44fa-998c-300daf732443.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjI3NDgsIm5iZiI6MTcxMjA2MjQ0OCwicGF0aCI6Ii8xNzQ0NTY1MS8zMTg2NDY0MDQtNGY2MzQ1MzItMmYyNi00NGZhLTk5OGMtMzAwZGFmNzMyNDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDEyNTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NGFhMDBjOTIxNDlkOWM2NzIzMGY2NmE2YmQ0YzBhNTkwMGFjMWI5Mjg4Y2FkY2E2NTRhYTZlMWQyYWUxZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TP4Zr6ouJ1cr0QLdsGqX3GycO4gEWorfS-j5ApJmsRQ">

- I'll go ahead and add a reference to the conference paper. However, I did not add links to aux accumulation verification tests in this object. Specifically the test that you mentioned was performed using the aux accumulator. That is a different object and charge density should not be accumulated into an aux variable when solving Poisson's equation so I have not referenced those tests in this documentation. 

- The reason for the weird asymmetry in the visualization of this field is because of the way paraview does its triangularization when filling in the gaps between the basis functions. A similar discussion came up with Derek during the paper review and this is just a visualization artifact and he said if we were to use the super sampler MOOSE object we would see a better visualization of the field. The most important thing for this case though is that the value of the field at the nodes is correct.

2024-04-02 13:28 UTC, loganharbour commented
I can take a look this evening!

2024-04-02 13:39 UTC, simopier commented
> The reason for the weird asymmetry in the visualization of this field is because of the way paraview does its triangularization when filling in the gaps between the basis functions. A similar discussion came up with Derek during the paper review and this is just a visualization artifact and he said if we were to use the super sampler MOOSE object we would see a better visualization of the field. The most important thing for this case though is that the value of the field at the nodes is correct.

I remember this discussion. But how did you get to look symmetrical in your paper, then? You already had this figure before we had this discussion.
You're right that what matters is the values at the nodes.

2024-04-02 13:45 UTC, gsgall commented
> > The reason for the weird asymmetry in the visualization of this field is because of the way paraview does its triangularization when filling in the gaps between the basis functions. A similar discussion came up with Derek during the paper review and this is just a visualization artifact and he said if we were to use the super sampler MOOSE object we would see a better visualization of the field. The most important thing for this case though is that the value of the field at the nodes is correct.
> 
> I remember this discussion. But how did you get to look symmetrical in your paper, then? You already had this figure before we had this discussion. You're right that what matters is the values at the nodes.

In creating my figure I exported the data from exodus to csv and then used matplotlib to visualize the data. Matplotlib must use a different triangularization or other technique for interpolation between known values when creating heat maps resulting in a symmetric figure.

2024-04-02 13:46 UTC, simopier reviewed
Looks good to me, but I'll wait until @loganharbour gave it a review because he'll bring a valuable perspective.

2024-04-02 13:49 UTC, simopier commented on src/userobjects/ChargeAccumulator.C
> +  // You need to add this exec flag so it can contribute to residuals
Either or, really. If we leave them, it could be good to make them a bit more formal:
- `These parameters are necessary when using ResidualAccumulator`
- `This exec flag is necessary for it to contribute to residuals`

or something like that. Not a hill I'll die on, though.

2024-04-08 22:40 UTC, loganharbour commented on include/userobjects/ChargeAccumulator.h
> +#include "PICStudyBase.h"
```suggestion

class PICStudyBase;
```

Should be sufficient + including in the source

2024-04-08 22:40 UTC, loganharbour commented on src/userobjects/ChargeAccumulator.C
> +  // Make sure that you add these params when using the ResidualAccumulator
I think that this is fine

2024-04-08 22:40 UTC, loganharbour commented on src/userobjects/ChargeAccumulator.C
> +{
Should we do some error checking here on whether or not the exec flags are set to what we'd expect them to be? Or, we can remove "execute_on" from being allowed to be set by the user

2024-04-09 00:22 UTC, gsgall commented on src/userobjects/ChargeAccumulator.C
> +  // You need to add this exec flag so it can contribute to residuals
Logan says they look fine I'll make them a little more formal for you as well

2024-04-09 00:24 UTC, gsgall commented on src/userobjects/ChargeAccumulator.C
> +{
I'll go ahead and just set the execute_on parameter for the user. I think it'll be the best way to avoid any sort of confusion.

2024-04-09 00:48 UTC, loganharbour commented on src/userobjects/ChargeAccumulator.C
> +{
sounds good. you can also suppress the parameter from being set by the user.

2024-04-09 00:50 UTC, gsgall commented on src/userobjects/ChargeAccumulator.C
> +{
Sounds good!

2024-04-09 01:01 UTC, gsgall commented on include/userobjects/ChargeAccumulator.h
> +#include "PICStudyBase.h"
I have made this change but I also had to include "Ray.h" after removing "#include PICStudyBase.h" since this class has a `RayDataIndex` member variable.

2024-04-09 01:03 UTC, loganharbour approved these changes

2024-04-09 03:57 UTC, simopier approved these changes
Thank you @gsgall and @loganharbour, this looks good to me.

2024-04-09 03:57 UTC, merged