Add Code Contribution Documentation
idaholab/fenix pull request #3
Opened 2023-11-09 17:14 UTC by cticenhour

This PR takes @simopier's contributing guidelines, makes some adjustments to add more information on code standards, cloning, and git remotes, and then formats it using proper MooseDown. A link is provided for this page from the navigation bar.

Refs #2

2023-11-09 17:20 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1882555/) on 5a9505a wanted to post the following:

View the site [here](https://salamander-dev.hpc.inl.gov/PRs/3/site)

This comment will be updated on new commits.

2023-11-09 17:20 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1882559/) on 5a9505a wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://salamander-dev.hpc.inl.gov/PRs/3/coverage)



This comment will be updated on new commits.

2023-11-09 17:30 UTC, cticenhour commented
Tagging @loganharbour to give input on the coverage generation failure. I invalidated once as a double-check, but this made no difference.

2023-11-13 23:10 UTC, simopier requested changes
Thank you @cticenhour for this contribution! And thank you @loganharbour for getting me access to the doc. 

I only have small edits. I wasn't able to figure out how to make some of my suggestions clear due to the ambiguity of the triple '`'. Sorry about that.

2023-11-13 23:10 UTC, simopier commented on doc/content/sqa/contributing.md
> +your changes. However, you will need to list an issue number in one of your commits! To get started:
```suggestion
should be created. This can be done ahead of time when developing code, or anytime before pushing
your changes. In any case, you will need to list an issue number in one of your commits! To get started:
```

2023-11-13 23:10 UTC, simopier commented on doc/content/sqa/contributing.md
> +1. Clone your new fork to your local machine using the following command (this assumes you have SSH set up on your GitHub account):
```suggestion
1. Clone your new fork to your local machine using the following command (this assumes you [have SSH set up on your GitHub account](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account)):
```

2023-11-13 23:10 UTC, simopier commented on doc/content/sqa/contributing.md
> +1. In your terminal, go to your application: `cd ~/projects/fenix`
I cannot figure out how to do it in suggestion because it keeps thinking I am done with my suggestion, but I think it should be:

1. In your terminal, go to your application:
   ```
   cd ~/projects/fenix
   ```

2023-11-13 23:10 UTC, simopier commented on doc/content/sqa/contributing.md
> +1. It is usually best to make sure your changes are based on devel: `git checkout devel`
Same here, it should be on a new line with the three '`'

2023-11-13 23:10 UTC, simopier commented on doc/content/sqa/contributing.md
> +1. Create new branch: `git checkout -b <BRANCH_NAME>`
Same here, the command should be surrounded by the three '`'. Sorry, I really cannot figure out how to add the proper suggestion, it keep thinking that I am done with my suggestion when I use the three '`'.

2023-11-13 23:10 UTC, simopier commented on doc/content/sqa/contributing.md
> +1. In your terminal, go to your application: `cd ~/projects/fenix`
Same comment here.

2023-11-13 23:10 UTC, simopier commented on doc/content/sqa/contributing.md
> +1. Type `git status` to see the status of your branch. - that should show you the changed files and
```suggestion
1. Type `git status` to see the status of your branch. That should show you the changed files and
```

2023-11-13 23:10 UTC, simopier commented on doc/content/sqa/contributing.md
> +1. Now you’re ready to commit. Run `git commit`.
Same comment here for the command.

2023-11-13 23:10 UTC, simopier commented on doc/content/sqa/contributing.md
> +1. At some point, you’ll be ready to push your work to your fork (remember, it has the remote name `origin`): run `git push origin <BRANCH_NAME>`
Same comment here for the command.

2023-11-15 14:07 UTC, simopier approved these changes
Looks great to me!

2023-11-15 14:09 UTC, merged