Fill in empty fields in SQA documentation
idaholab/fenix pull request #31
Opened 2024-04-25 15:27 UTC by cticenhour

Refs #2

2024-04-25 15:34 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2196172/) on 38b0e6f wanted to post the following:

View the site [here](https://fenix-dev.hpc.inl.gov/PRs/31/site)

This comment will be updated on new commits.

2024-04-25 15:36 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2196176/) on 38b0e6f wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://fenix-dev.hpc.inl.gov/PRs/31/coverage)



This comment will be updated on new commits.

2024-04-25 23:32 UTC, simopier requested changes
Thank you for adding this information! I only have very minor comments and questions.

2024-04-25 23:32 UTC, simopier commented on doc/content/sqa/fenix_sdd.md
> +- [Ray Tracing](ray_tracing/index.md)
We'll need to make sure to keep that list updated.

2024-04-25 23:32 UTC, simopier commented on doc/content/sqa/fenix_srs.md
> +  heat conduction,  and/or material science as well as in modeling and simulation techniques, but may have
```suggestion
  heat conduction, and/or material science as well as in modeling and simulation techniques, but may have
```

2024-04-25 23:32 UTC, simopier commented on doc/content/sqa/fenix_srs.md
> +The regression test suite will cover at least 87% of all lines of code at all times. Known
Re: 87%: Is it where we are now?
Otherwise I think we should round it up to 90%.

2024-04-25 23:33 UTC, simopier commented on doc/content/sqa/fenix_srs.md
> +  heat conduction,  and/or material science as well as in modeling and simulation techniques, but may have
When I said very minor, I meant it! 😉

2024-04-26 14:49 UTC, cticenhour commented on doc/content/sqa/fenix_sdd.md
> +- [Ray Tracing](ray_tracing/index.md)
Yes - along with the other "scoping" sections of these documents as the app grows and changes. However, I am OK with removing this list if you want to do so. We do the same thing in TMAP8 as we do here.

2024-04-26 14:49 UTC, cticenhour commented on doc/content/sqa/fenix_srs.md
> +The regression test suite will cover at least 87% of all lines of code at all times. Known
This is where we are now. I will check the most recent coverage figure to see if we can bump it. This should be aligned with our CI-set coverage guidelines, even if a round number is prettier :)

2024-04-26 14:59 UTC, cticenhour commented on doc/content/sqa/fenix_srs.md
> +The regression test suite will cover at least 87% of all lines of code at all times. Known
![image](https://github.com/idaholab/fenix/assets/16690058/15ccd6bd-9967-4094-bd25-ef7e0470e3ee)

Looks like we are currently at 92% coverage! https://civet.inl.gov/job/2195884/

I will bump this and the `.coverage` file to 90% 😄

2024-04-26 16:33 UTC, simopier commented on doc/content/sqa/fenix_srs.md
> +The regression test suite will cover at least 87% of all lines of code at all times. Known
Love to see it!

2024-04-26 16:34 UTC, simopier approved these changes
Great addition, thanks!

2024-04-26 16:34 UTC, merged

2024-04-26 16:36 UTC, simopier commented on doc/content/sqa/fenix_sdd.md
> +- [Ray Tracing](ray_tracing/index.md)
I'm good having it here (just as we do in TMAP8, as you mentioned), I think it's useful documentation.

We'll just need to periodically check and update. This was more a "thinking out loud" comment rather than a request. 😄