Uniform Particle Initialization
idaholab/fenix pull request #37
Opened 2024-05-24 22:14 UTC by gsgall

Closes #36 

Additionally this renames ChargeAccumulator to ChargeDensityAccumulator for clarity and slightly modifies the implementation for correctness. 

A few other small fixes were made as well, adding a few more comments and changing instances of `ray->data()[index]` to `ray->data(index)` to promote best practices by future develops looking for examples.

2024-05-24 22:37 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2256585/) on db259d8 wanted to post the following:

View the site [here](https://fenix-dev.hpc.inl.gov/PRs/37/site)

This comment will be updated on new commits.

2024-05-26 04:39 UTC, simopier requested changes
Awesome contribution!

Not a complete review, but that'll be a good place for you to start. I did not yet get to try to figure out why some exodiff are happening, though.

2024-05-26 04:39 UTC, simopier commented on doc/content/source/kernels/ProjectionKernel.md
> +This kernel represent the first term in the above equation and in FENIX is generally used for solving for the project of discrete, on particle, quantities onto the finite element mesh.
```suggestion
This kernel represent the first term in the above equation and in FENIX is generally used for solving for the projection of discrete - on particle - quantities onto the finite element mesh.
```

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +      "density, particles per element and the elements \"volume\"");
```suggestion
      "density, particles per element, and the elements \"volume\".");
```

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +      "element and calculates the corrisponding particle weight based on the requested number "
```suggestion
      "element and calculates the corresponding particle weight based on the requested number "
```

2024-05-26 04:39 UTC, simopier commented on doc/content/source/userobjects/ParticlesPerElementInitializer.md
> +Because the charge density in FENIX is defined by delta functions and each computational particle represents some number of physical particles computational particles are assigned a weight $\omega_i$
```suggestion
Because the charge density in FENIX is defined by Dirac delta functions and each computational particle represents some number of physical particles, computational particles are assigned a weight $\omega_i$. In cartesian geometry this weight represents the number of physical particles per \[m$^{3-d}$\] where $d$ is the dimension of the problem.
```

2024-05-26 04:39 UTC, simopier commented on doc/content/source/userobjects/ParticlesPerElementInitializer.md
> +  }
```suggestion
  },
```

2024-05-26 04:39 UTC, simopier commented on doc/content/source/userobjects/ParticlesPerElementInitializer.md
> +    N \; V
```suggestion
    N \; V_j
```

2024-05-26 04:39 UTC, simopier commented on doc/content/source/userobjects/ParticlesPerElementInitializer.md
> +In this object the the particle weight is given by
```suggestion
In this object the weight of the $j^(th)$ particle is given by
```

2024-05-26 04:39 UTC, simopier commented on doc/content/source/userobjects/ParticlesPerElementInitializer.md
> +# Example Input Syntax
```suggestion
## Example Input Syntax
```

2024-05-26 04:39 UTC, simopier commented on doc/content/source/userobjects/ParticlesPerElementInitializer.md
> +Because the charge density in FENIX is defined by delta functions and each computational particle represents some number of physical particles computational particles are assigned a weight $\omega_i$
```suggestion
## Overview

Because the charge density in FENIX is defined by delta functions and each computational particle represents some number of physical particles computational particles are assigned a weight $\omega_i$. In cartesian geometry this weight reprsents the number of physical particles per \[m$^{3-d}$\] where $d$ is the dimension of the problem.
```

2024-05-26 04:39 UTC, simopier commented on doc/content/source/kernels/ProjectionKernel.md
> +In general the projection of a function onto finite element basis functions is defined by
```suggestion
## Overview

In general the projection of a function onto finite element basis functions is defined by
```

2024-05-26 04:39 UTC, simopier commented on doc/content/source/kernels/ProjectionKernel.md
> +!listing test/tests/userobjects/particles_per_element_initializer/elements/1d.i block=Kernels
```suggestion
## Example Input Syntax

!listing test/tests/userobjects/particles_per_element_initializer/elements/1d.i block=Kernels
```

2024-05-26 04:39 UTC, simopier commented on doc/content/source/userobjects/ChargeDensityAccumulator.md
>  In FENIX the charge density $\rho$ is defined as
```suggestion
## Overview

In FENIX the charge density $\rho$ is defined as
```

2024-05-26 04:39 UTC, simopier commented on doc/content/source/userobjects/ChargeDensityAccumulator.md
>  !listing test/tests/userobjects/charge_accumulation/simple_potential_solve.i block=UserObjects
```suggestion
## Example Input Syntax

!listing test/tests/userobjects/charge_accumulation/simple_potential_solve.i block=UserObjects
```

2024-05-26 04:39 UTC, simopier commented on include/kernels/ProjectionKernel.h
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
```suggestion
//* This file is part of FENIX: Fusion Energy Integrated Multiphys-X,
//* A multiphysics application for modeling plasma facing components
//* https://github.com/idaholab/fenix
//*
//* FENIX is powered by the MOOSE Framework
//* https://www.mooseframework.inl.gov
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html
```

2024-05-26 04:39 UTC, simopier commented on include/userobjects/InitializerBase.h
> +  virtual void execute() override final {}
Just making sure to point out to check if these are needed here if they are not needed.

2024-05-26 04:39 UTC, simopier commented on src/kernels/ProjectionKernel.C
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
```suggestion
//* This file is part of FENIX: Fusion Energy Integrated Multiphys-X,
//* A multiphysics application for modeling plasma facing components
//* https://github.com/idaholab/fenix
//*
//* FENIX is powered by the MOOSE Framework
//* https://www.mooseframework.inl.gov
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html
```

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +    paramError("number_density", "The requested number density cannot be zero.");
```suggestion
  if (_number_density <= 0.0)
    paramError("number_density", "The requested number density must be >= 0.");
```
Or could it really be negative?

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +    paramError("particles_per_element", "The number of particles in each element must be >= 0");
```suggestion
    paramError("particles_per_element", "The number of particles in each element must be >= 0.");
```

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +  for ([[maybe_unused]] const auto elem : *_fe_problem.mesh().getActiveLocalElementRange())
What is `maybe_unused` doing here?

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +  // in case there are no elements for this processor do nothing
```suggestion
  // if there are no elements for this processor: do nothing
```

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +  // setting up this to be able to map from reference elemnts to the physical elemnts
```suggestion
  // setting up this to be able to map from reference elements to the physical elements
```

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +    // we need to find which one it is is in
```suggestion
    // we need to find which one it is in
```

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +        auto temp = p(1);
```suggestion
        auto temporary = p(1);
```
To avoid confusion with `temperature`. I know there are no temperature here, but this is a pet peeve of mine...

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +        p(2) = temp;
```suggestion
        p(2) = temporary;
```

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +        auto temp = p(0);
```suggestion
        auto temporary = p(0);
```

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +        p(2) = temp;
```suggestion
        p(2) = temporary;
```

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +    // the correct orientataion to match the reference element
```suggestion
    // the correct orientation to match the reference element
```

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +      // 3D elements with all trianglular faces with nodes at
```suggestion
      // 3D elements with all triangular faces with nodes at
```

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +          put_particle_in_pyramid(reference_points[i]);
```suggestion
          // start by folding the cube into a pyramid
          put_particle_in_pyramid(reference_points[i]);
```

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +          // at this point we have two tetrahedrons and we need to reflect on of them
```suggestion
          // at this point we have two tetrahedrons and we need to reflect one of them
```

2024-05-26 04:39 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +          // to make this our refcerence tet we perform an affine tranformation
```suggestion
          // to make this our reference tet we perform an affine transformation
```

2024-05-26 04:39 UTC, simopier commented on test/include/distributions/Constant.h
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
```suggestion
//* This file is part of FENIX: Fusion Energy Integrated Multiphys-X,
//* A multiphysics application for modeling plasma facing components
//* https://github.com/idaholab/fenix
//*
//* FENIX is powered by the MOOSE Framework
//* https://www.mooseframework.inl.gov
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html
```

2024-05-26 04:39 UTC, simopier commented on test/src/distributions/Constant.C
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
```suggestion
//* This file is part of FENIX: Fusion Energy Integrated Multiphys-X,
//* A multiphysics application for modeling plasma facing components
//* https://github.com/idaholab/fenix
//*
//* FENIX is powered by the MOOSE Framework
//* https://www.mooseframework.inl.gov
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html
```

2024-05-26 04:39 UTC, simopier commented on test/src/userobjects/TestInitializedPICStudy.C
> +  // incase there are no rays on this processor, do nothing
```suggestion
  // if there are no rays on this processor: do nothing
```

2024-05-26 04:39 UTC, simopier commented on test/src/userobjects/TestInitializedPICStudy.C
> +  // this counter will be used to incriment the ray id on a per element basis
```suggestion
  // this counter will be used to increment the ray id on a per element basis
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/1d.i
> +particles_per_element = 10
Please add a short comment about what this input does.

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/1d.i
> +  elem_type = EDGE2
```suggestion
    type = GeneratedMeshGenerator
    dim = 1
    nx = 10
    xmax = 1
    elem_type = EDGE2
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/2d.i
> +particles_per_element = 10
I encourage you to leverage the `include` capabilities to create a base input file that contains all the blocks shared by the 1d, 2d, and 3d input files and have `1d.i`, `2d.i`, and `3d.i` only containing the information specific to them. This will make maintenance easier and will clarify what needs to change from 1d to 2d to 3d.

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/tests
> +      detail = "and solve an electrostatic potenteial based on the particle positions"
```suggestion
      detail = "and solve an electrostatic potential based on the particle positions"
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/tests
> +      detail = "and compute the error between an exact electrostic potential and the finite element solution"
```suggestion
      detail = "and compute the error between an exact electrostatic potential and the finite element solution"
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/tests
> +      detail = "and solve an electrostatic potenteial based on the particle positions"
```suggestion
      detail = "and solve an electrostatic potential based on the particle positions"
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/tests
> +      detail = "and compute the error between an exact electrostic potential and the finite element solution"
```suggestion
      detail = "and compute the error between an exact electrostatic potential and the finite element solution"
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/tests
> +      detail = "and solve an electrostatic potenteial based on the particle positions"
```suggestion
      detail = "and solve an electrostatic potential based on the particle positions"
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/tests
> +      detail = "and compute the error between an exact electrostic potential and the finite element solution"
```suggestion
      detail = "and compute the error between an exact electrostatic potential and the finite element solution"
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/tests
> +      detail = "and solve an electrostatic potenteial based on the particle positions"
```suggestion
      detail = "and solve an electrostatic potential based on the particle positions"
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/tests
> +      detail = "and compute the error between an exact electrostic potential and the finite element solution"
```suggestion
      detail = "and compute the error between an exact electrostatic potential and the finite element solution"
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/tests
> +      detail = "and solve an electrostatic potenteial based on the particle positions"
```suggestion
      detail = "and solve an electrostatic potential based on the particle positions"
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/tests
> +      detail = "and compute the error between an exact electrostic potential and the finite element solution"
```suggestion
      detail = "and compute the error between an exact electrostatic potential and the finite element solution"
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/tests
> +      detail = "and solve an electrostatic potenteial based on the particle positions"
```suggestion
      detail = "and solve an electrostatic potential based on the particle positions"
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/tests
> +      detail = "and compute the error between an exact electrostic potential and the finite element solution"
```suggestion
      detail = "and compute the error between an exact electrostatic potential and the finite element solution"
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/tests
> +      detail = "and solve an electrostatic potenteial based on the particle positions"
```suggestion
      detail = "and solve an electrostatic potential based on the particle positions"
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/tests
> +      detail = "and compute the error between an exact electrostic potential and the finite element solution"
```suggestion
      detail = "and compute the error between an exact electrostatic potential and the finite element solution"
```

2024-05-26 04:39 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/errors/tests
> +      expect_err = 'The requested number density cannot be zero.'
Adapt based on potential changes above.

2024-05-26 04:47 UTC, gsgall commented
> Awesome contribution!
> 
> Not a complete review, but that'll be a good place for you to start. I did not yet get to try to figure out why some exodiff are happening, though.

Thanks for the review! 

I am planning on trying to debug the test errors on Tuesday with a linux machine. All of the tests pass when I run them locally. My first guess is that this is because element ids are assigned differently on linux for some reason.

2024-05-29 17:15 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2256589/) on db259d8 wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>19b735</th>
      <th colspan=4>#37 db259d</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>92.39%</td>
      <td>93.60%</td>
      <td>+1.21%</td>
      <td>95.98%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>255</td>
      <td>395</td>
      <td>+140</td>
      <td>167</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>21</td>
      <td>27</td>
      <td>+6</td>
      <td>7</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://fenix-dev.hpc.inl.gov/PRs/37/coverage_diff)

[Full coverage report](https://fenix-dev.hpc.inl.gov/PRs/37/coverage)



This comment will be updated on new commits.

2024-05-29 19:43 UTC, gsgall commented
> > Awesome contribution!
> > Not a complete review, but that'll be a good place for you to start. I did not yet get to try to figure out why some exodiff are happening, though.
> 
> Thanks for the review!
> 
> I am planning on trying to debug the test errors on Tuesday with a linux machine. All of the tests pass when I run them locally. My first guess is that this is because element ids are assigned differently on linux for some reason.

It turned out that the issue with passing tests from the original PR was the way I was initializing random points. 

In the original PR I had something like this for TRI3 and PRISM6 elements 

```
   reference_points[i] = Point(generator.rand(), generator.rand(), 0.0);
```

After looking into this more on linux the issue was that when this point object was created on linux the random sampling executed in a different order than on my local Mac machine. If the result on my computer was something like this 

Points = (0.5, 0.6, 0.0) 

Then the result on linux would be 

Points = (0.6 0.5, 0.0) 

The fix for this is pretty simple just assign values in the order desired 

```
reference_points[i](0) = generator.rand(); 
reference_points[i](1) = generator.rand(); 
```

it must have just come down to a difference in the compilers being used.

2024-05-29 19:49 UTC, gsgall commented on include/userobjects/InitializerBase.h
> +  virtual void execute() override final {}
We need to override these because they are virtual in the GeneralUserObject class.

2024-05-29 19:51 UTC, gsgall commented on src/userobjects/ParticlesPerElementInitializer.C
> +  for ([[maybe_unused]] const auto elem : *_fe_problem.mesh().getActiveLocalElementRange())
Since I am iterating over the elements but not actually using the variable `elem` the `[maybe_unused]` suppresses the warning about the variable `elem` being unused in this loop.

2024-05-29 20:15 UTC, simopier commented
> > > Awesome contribution!
> > > Not a complete review, but that'll be a good place for you to start. I did not yet get to try to figure out why some exodiff are happening, though.
> > 
> > 
> > Thanks for the review!
> > I am planning on trying to debug the test errors on Tuesday with a linux machine. All of the tests pass when I run them locally. My first guess is that this is because element ids are assigned differently on linux for some reason.
> 
> It turned out that the issue with passing tests from the original PR was the way I was initializing random points.
> 
> In the original PR I had something like this for TRI3 and PRISM6 elements
> 
> ```
>    reference_points[i] = Point(generator.rand(), generator.rand(), 0.0);
> ```
> 
> After looking into this more on linux the issue was that when this point object was created on linux the random sampling executed in a different order than on my local Mac machine. If the result on my computer was something like this
> 
> Points = (0.5, 0.6, 0.0)
> 
> Then the result on linux would be
> 
> Points = (0.6 0.5, 0.0)
> 
> The fix for this is pretty simple just assign values in the order desired
> 
> ```
> reference_points[i](0) = generator.rand(); 
> reference_points[i](1) = generator.rand(); 
> ```
> 
> it must have just come down to a difference in the compilers being used.

Great catch and fix, thanks for the detailed explanation!

2024-05-29 20:20 UTC, gsgall commented on src/userobjects/ParticlesPerElementInitializer.C
> +    paramError("number_density", "The requested number density cannot be zero.");
It could be depending on the user input. The number density should be a float and since there are no unsigned floats we need to perform a check for negative values.

2024-05-29 20:23 UTC, gsgall commented on doc/content/source/userobjects/ParticlesPerElementInitializer.md
> +Because the charge density in FENIX is defined by delta functions and each computational particle represents some number of physical particles computational particles are assigned a weight $\omega_i$
Couldn't apply this automatically so it was done manually.

2024-05-29 20:25 UTC, gsgall commented on src/userobjects/ParticlesPerElementInitializer.C
> +    paramError("number_density", "The requested number density cannot be zero.");
The number of particles per element on the other hand should never be zero so I will adjust that error message accordingly.

2024-05-29 20:40 UTC, gsgall commented on test/tests/userobjects/particles_per_element_initializer/elements/2d.i
> +particles_per_element = 10
Thank you for letting me know about this. I have updated the files to use this syntax.

2024-05-29 21:05 UTC, simopier requested changes
Things are looking very good! These are just a minor change because I think the if tests and the errors are sometimes inconsistent (and we need to pick if we want to enable 0.0 values or not - I'll let you pick, my suggestions only ensures that the test and error are consistent).

Also, I would like to have a meeting with you and @cticenhour (maybe @loganharbour if we have it once he is back) to discuss about how you ensured that the particle initialization is uniform, and what the tests are testing exactly. 
I know you've been doing a lot in this area and want to make sure we discuss it until I'm fully convinced everything is working well.

2024-05-29 21:05 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +  if (_particles_per_element == 0)
```suggestion
  if (_particles_per_element <= 0)
```

2024-05-29 21:05 UTC, simopier commented on src/userobjects/InitializerBase.C
> +    paramError("mass", "The mass of particles must be >= 0.0");
```suggestion
  if (_mass < 0.0)
    paramError("mass", "The mass of particles must be >= 0.0");
```

2024-05-29 21:05 UTC, simopier commented on src/userobjects/ParticlesPerElementInitializer.C
> +  if (_number_density <= 0.0)
```suggestion
  if (_number_density < 0.0)
```

2024-05-29 21:21 UTC, gsgall commented on src/userobjects/ParticlesPerElementInitializer.C
> +  if (_particles_per_element == 0)
The particles per element is an `unsigned int` if a negative value is provided here then a MOOSE error is thrown during input file parsing so including the less than in this comparison would never be executed.

2024-05-29 21:23 UTC, gsgall commented on src/userobjects/ParticlesPerElementInitializer.C
> +  if (_number_density <= 0.0)
Number density should never be zero so I am updating the error message to be consistent.

2024-05-29 21:24 UTC, gsgall commented on src/userobjects/InitializerBase.C
> +    paramError("mass", "The mass of particles must be >= 0.0");
Mass should also never be zero so I will update this message to be more clear as well.

2024-05-31 14:23 UTC, simopier approved these changes
Thank you for this contribution! It looks good to me.

2024-05-31 14:24 UTC, merged

2024-06-03 13:45 UTC, loganharbour commented
I still have quite a few comments for this

2024-06-04 13:50 UTC, loganharbour commented on src/userobjects/InitializerBase.C
> +  params.addParam<Real>("charge", 1, "The charge of the particles used for a test");
Why is the word "test" used in a non-test object?

2024-06-04 13:50 UTC, loganharbour commented on src/userobjects/InitializerBase.C
> +  params.addParam<std::string>("species", "", "The type of particle that is being initialized");
This should be an enum

2024-06-04 13:50 UTC, loganharbour commented on src/userobjects/InitializerBase.C
> +    paramError("mass", "The mass of particles must be > 0.0");
You can use `addRangeCheckedParam` in `validParams()` for simple checks like this.

Applies to most of the param errors you have in here

2024-06-04 13:50 UTC, loganharbour commented on src/userobjects/ParticlesPerElementInitializer.C
> +    num_local_elements++;
```
const auto & elem_range = *_fe_problem.mesh().getActiveLocalElementRange();
const auto num_local_elements = std::distance(elem_range.begin(), elem_range.end());

2024-06-04 13:50 UTC, loganharbour commented on src/userobjects/ParticlesPerElementInitializer.C
> +      // 1D reference elements x = [-1, 1]
Most of the information here in regard to the reference space can actually be obtained via libmesh without the need for most of this custom logic, which is probably a good idea as this is a bit error prone

2024-06-04 20:10 UTC, gsgall commented on src/userobjects/InitializerBase.C
> +  params.addParam<Real>("charge", 1, "The charge of the particles used for a test");
Good catch I have removed this.

2024-06-04 20:13 UTC, gsgall commented on src/userobjects/InitializerBase.C
> +  params.addParam<std::string>("species", "", "The type of particle that is being initialized");
Can we still use an enum if this input can be arbitrary?

2024-06-04 20:24 UTC, gsgall commented on src/userobjects/InitializerBase.C
> +  params.addParam<std::string>("species", "", "The type of particle that is being initialized");
In general we have no way of knowing all of the different types of particles that will exist in any given plasma simulation.

2024-06-04 20:44 UTC, gsgall commented on src/userobjects/ParticlesPerElementInitializer.C
> +    num_local_elements++;
This has also been added. 

Thanks for this as well I tried doing it earlier but it wasn't working now I see the issue was that I wasn't storing `elem_range` as a reference.

2024-06-04 20:53 UTC, gsgall commented on src/userobjects/InitializerBase.C
> +    paramError("mass", "The mass of particles must be > 0.0");
Thank you for telling me about this I didn't know this functionality was available! I will update my objects to use this.

2024-06-04 21:04 UTC, gsgall commented on src/userobjects/ParticlesPerElementInitializer.C
> +      // 1D reference elements x = [-1, 1]
Can you explain a bit more about what functionality I should be using rather than what I am doing now?