Copyright notice
idaholab/fenix pull request #45
Opened 2024-06-14 15:35 UTC by simopier

(Close. #44)

2024-06-14 15:39 UTC, simopier commented
@inl-labtrack for you to check that everything is done right.

2024-06-14 15:46 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2277358/) on 77892dd wanted to post the following:

View the site [here](https://fenix-dev.hpc.inl.gov/PRs/45/site)

This comment will be updated on new commits.

2024-06-14 15:47 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2277362/) on 77892dd wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>ba09b7</th>
      <th colspan=4>#45 77892d</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>93.62%</td>
      <td>93.69%</td>
      <td>+0.07%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>396</td>
      <td>401</td>
      <td>+5</td>
      <td>5</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>27</td>
      <td>27</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://fenix-dev.hpc.inl.gov/PRs/45/coverage_diff)

[Full coverage report](https://fenix-dev.hpc.inl.gov/PRs/45/coverage)



This comment will be updated on new commits.

2024-06-14 16:48 UTC, cticenhour requested changes

2024-06-14 16:48 UTC, cticenhour commented on include/base/FenixApp.h
> +//* https://github.com/idaholab/fenix
```suggestion
//* https://github.com/idaholab/fenix
//* https://mooseframework.inl.gov/fenix
```
I would consider also adding the URL to what-will-be the open FENIX website. Commenting once since you have a script to update the rest. This is optional, since the website isn't live yet and we could push another PR.

2024-06-14 16:48 UTC, cticenhour commented on scripts/fixup_headers.py
> +# first to make sure there is a clean dry run of the files that should
```suggestion
# first to make sure there is a clean dry-run of the files that should
```

2024-06-14 16:48 UTC, cticenhour commented on scripts/fixup_headers.py
> +# https://github.com/idaholab/moose/blob/master/framework/scripts/fixup_headers.py
Probably should use a permalink instead of the most-current link, since this file is not guaranteed to be in master forever (though highly unlikely to be removed at this point).

2024-06-14 16:48 UTC, cticenhour commented on scripts/fixup_headers.py
> +//*"""
Python uses a different comment symbol.

```suggestion
#* This file is part of FENIX: Fusion ENergy Integrated multiphys-X,
#* A multiphysics application for modeling plasma facing components
#* https://github.com/idaholab/fenix
#*
#* FENIX is powered by the MOOSE Framework
#* https://www.mooseframework.inl.gov
#*
#* Licensed under LGPL 2.1, please see LICENSE for details
#* https://www.gnu.org/licenses/lgpl-2.1.html
#*
#* Copyright 2024, Battelle Energy Alliance, LLC
#* ALL RIGHTS RESERVED
#*"""
```

2024-06-14 16:48 UTC, cticenhour commented on scripts/fixup_headers.py
> +global_dir_ignores = ['contrib', '.svn', '.git', 'crane', 'moose', 'squirrel']
```suggestion
global_dir_ignores = ['contrib', '.svn', '.git', 'moose']
```

Removing remnants from the Zapdos origin of this file.

2024-06-14 16:48 UTC, cticenhour commented on scripts/fixup_headers.py
> +global_file_ignores = ['moosedocs.py']
```suggestion
global_file_ignores = ['moosedocs.py', 'fixup_headers.py']
```

Let's also make sure it ignores itself, if it doesn't already. If it ignored this file on first run, please disregard this adjustment.

2024-06-14 17:28 UTC, simopier commented on include/base/FenixApp.h
> +//* https://github.com/idaholab/fenix
I'll add it to all the headers now

2024-06-14 17:28 UTC, simopier commented on scripts/fixup_headers.py
> +# https://github.com/idaholab/moose/blob/master/framework/scripts/fixup_headers.py
Not sure what the permalink would be.

2024-06-14 17:28 UTC, simopier commented on scripts/fixup_headers.py
> +global_dir_ignores = ['contrib', '.svn', '.git', 'crane', 'moose', 'squirrel']
Good catch!

2024-06-14 17:28 UTC, simopier commented on scripts/fixup_headers.py
> +global_file_ignores = ['moosedocs.py']
The file ignores itself.

2024-06-14 17:34 UTC, simopier commented on include/base/FenixApp.h
> +//* https://github.com/idaholab/fenix
Done

2024-06-14 18:19 UTC, cticenhour commented on scripts/fixup_headers.py
> +# https://github.com/idaholab/moose/blob/master/framework/scripts/fixup_headers.py
If you navigate to the file on GitHub, click on the `...` button in the top right of the file viewer, then click on Copy Permalink. See:

<img width="625" alt="image" src="https://github.com/idaholab/fenix/assets/16690058/eb962a13-134c-42ab-bdf9-a246ff155f26">

In this case, this gives you a permalink of:

https://github.com/idaholab/moose/blob/c36c4a18fba0ccf92769bbaef5e6b2d2ba7a43c1/framework/scripts/fixup_headers.py

Which is the current version at a specific hash (so will be referenced exactly as today, even if master changes).

2024-06-14 19:56 UTC, simopier commented on scripts/fixup_headers.py
> +# https://github.com/idaholab/moose/blob/master/framework/scripts/fixup_headers.py
```suggestion
# https://github.com/idaholab/moose/blob/c36c4a18fba0ccf92769bbaef5e6b2d2ba7a43c1/framework/scripts/fixup_headers.py
```

2024-06-14 20:57 UTC, cticenhour approved these changes

2024-06-18 13:22 UTC, loganharbour approved these changes

2024-06-20 16:22 UTC, merged

2024-06-20 16:23 UTC, simopier commented
@inl-labtrack confirmed the approval from @loganharbour and @cticenhour was enough.