Implementation of simple dimension dependent particle stepping
idaholab/fenix pull request #7
Opened 2023-11-23 01:55 UTC by gsgall

closes #4

2023-11-24 22:45 UTC, loganharbour commented
You don't need to update the moose submodule, it's done automatically from our continuous integration suite at civet.inl.gov.

In general, you'll just want to rebase on the upstream (idaholab) remote of salamander to pull these changes in. If you setup the repo as we have it in the contributing docs (see https://github.com/idaholab/salamander/blob/devel/doc/content/sqa/contributing.md), the way to pull in the new content (i.e., moose submodule) would be:

```
git fetch upstream
git rebase upsteam/devel
```

Glad to help with this more, I'm just not sure as to what your level of comfort is with git

2023-11-24 22:56 UTC, gsgall commented
I would say I have moderate comfort with using git I have used it while pushing and pulling but rebasing and merging are still somewhat unfamiliar territory for me. 

I've just tried a to rebase my fork with 

```
git remote add upstream git@github.com:idaholab/salamander.git
git fetch upstream
```

And I got a permission denied message 

```git rebase upsteam/devel
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: invalid upstream 'upsteam/devel'
```

I thought I should have permission for this repo so I am not sure what the issue with this is.

2023-11-24 23:48 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1956906/) on 2959c0e wanted to post the following:

View the site [here](https://salamander-dev.hpc.inl.gov/PRs/7/site)

This comment will be updated on new commits.

2023-11-25 22:05 UTC, simopier commented
@gsgall could you run

```
cd ~/projects/salamander
git remote -v 
```

and share what comes up?

2023-11-26 00:57 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1956910/) on 2959c0e wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>f6073a</th>
      <th colspan=4>#7 2959c0</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>50.00%</td>
      <td>82.22%</td>
      <td>+32.22%</td>
      <td>96.77%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>14</td>
      <td>74</td>
      <td>+60</td>
      <td>60</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>14</td>
      <td>16</td>
      <td>+2</td>
      <td>2</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://salamander-dev.hpc.inl.gov/PRs/7/coverage_diff)

[Full coverage report](https://salamander-dev.hpc.inl.gov/PRs/7/coverage)



This comment will be updated on new commits.

2023-11-26 04:18 UTC, gsgall commented
Sorry about the bumpy start. The issue was that I had updated the submodule on my branch and then pushed rather than just rebasing wih the salamander repo. I had to delete a few commits where that included the moose submodule update and then set up  the salamander repo as the upstream of my fork with the following commands.  

```
git remote add upstream git@github.com:idaholab/salamander.git
git remote set-url upstream https://github.com/idaholab/salamander.git
git fetch upstream                                               
git rebase upsteam/devel
```

@loganharbour helped me sort out the issues I was having over slack. Really appreciate the support!

2023-11-30 23:08 UTC, loganharbour requested changes
Mostly minor changes except for the fundamental question of why the kernel is the way that it is

2023-11-30 23:08 UTC, loganharbour commented on include/raykernels/PICKernelBase.h
> +// Local Includes
```suggestion
```

Our standard typically dictates that first includes are the things you depend on, so this context isn't needed

2023-11-30 23:08 UTC, loganharbour commented on include/userobjects/PICStudyBase.h
> +  const RayDataIndex _direction_set_index;
All data members need to be protected. If you want to access them from outside of the class, create a method to access them. In general, we always avoid accessing member variables directly from outside of a class

2023-11-30 23:08 UTC, loganharbour commented on include/userobjects/PICStudyBase.h
> +  virtual void postExecuteStudy();
```suggestion
  virtual void postExecuteStudy() override;
```

I think?

2023-11-30 23:08 UTC, loganharbour commented on src/raykernels/PICKernelBase.C
> +// MOOSE includes
```suggestion

```

2023-11-30 23:08 UTC, loganharbour commented on include/userobjects/PICStudyBase.h
> +  virtual void generateRays();
```suggestion
  virtual void generateRays() override;
```

2023-11-30 23:08 UTC, loganharbour commented on src/raykernels/PICKernelBase.C
> +PICKernelBase::setDirectionAndMaxDistance(const Real dt)
What is the thought process for setting the velocity inside the kernel instead of systematically setting it from the study?

When we need to sample from the velocity field, that sampling will be done in the study and not the kernel. The kernel should act on things that happen along each segment of a trace, not things that happen just once.

2023-11-30 23:08 UTC, loganharbour commented on src/raykernels/PICKernelBase.C
> +  auto ray = currentRay();
Because you're not taking this as a reference, it's constructing a new `std::shared_ptr<Ray>` (which points to the same Ray). This is actually not a cheap operation. It's what we call an atomic operation, which is thread safe. Such operations aren't necessary here.

```
auto & ray 
```

is more appropriate

2023-11-30 23:08 UTC, loganharbour commented on src/userobjects/PICStudyBase.C
> +    _v_z_index(registerRayData("v_z")),
Do you always need to register y and z?

2023-11-30 23:08 UTC, loganharbour commented on src/userobjects/PICStudyBase.C
> +  _banked_rays = rayBank();
Add a comment here as to what this does, it's not the most straight forward

2023-11-30 23:08 UTC, loganharbour commented on test/src/userobjects/TestPICStudyBase.C
> +  params.set<bool>("_use_ray_registration") = false;
```suggestion
```
Already set in the base class

2023-11-30 23:08 UTC, loganharbour commented on src/raykernels/PICKernelBase.C
> +  ray->setStartingDirection(direction);
Yeah - this kind of thing should be done at the study level

2023-11-30 23:34 UTC, gsgall commented on src/userobjects/PICStudyBase.C
> +    _v_z_index(registerRayData("v_z")),
All velocity components do need to be tracked during simulation even in lower dimensions. I think storing this data in ray data is the most intuitive way to do this but we could also use a scheme like the following. 

- Always maintain a velocity magnitude in ray data
- In 3D no additional data is needed to store velocity data 
- In 2D store the z component as ray data 
- In 1D store the y, and z components as ray data 

But overall we do need to store all 3 components of velocity even when the geometry may be 1D. Let me know if you have a preference for storing all 3 components in ray data or in the manner described above.

2023-11-30 23:43 UTC, gsgall commented on src/raykernels/PICKernelBase.C
> +  ray->setStartingDirection(direction);
The thinking I had for modifying the direction and max distance settings for a ray in a RayKernel rather than in the Study was to allow for more flexibility in the particle stepping methods and have those be independent from the generation of particles. The first example I was thinking about for this would be for electrostatic versus electro magnetic PIC simulations. The particle push algorithm looks a little different between the two and I think it will reduce code replication if we have the kernels control that pushing algorithm for that reason. 

I can see another way forward with having the RayStudy control the velocity updating and the direction setting but what I could see happening if we do this is that the number of RayStudies could get a bit out of hand if want to offer a few different options for particle initialization algorithms. If the RayStudy controls the particle velocity update then we would need at a minimum two version of each study. One that uses the electric field alone update and one that uses the electromagnetic update. This would problem would also be worse if we wanted to investigate another particle stepping algorithms than the two standards, Leap Frog and Boris.

2023-12-01 00:59 UTC, cticenhour requested changes
@loganharbour has this well in hand, but I did notice one item I wanted to make sure I highlighted.

2023-12-01 00:59 UTC, cticenhour commented on include/raykernels/PICKernelBase.h
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
```suggestion
//* This file is part of FENIX: Fusion Energy Integrated Multiphys-X,
//* A multiphysics application for modeling plasma facing components
//* https://github.com/idaholab/fenix
//*
//* FENIX is powered by the MOOSE Framework
//* https://www.mooseframework.inl.gov
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html
```

We should create a FENIX file header instead of using the MOOSE one, and then replace all instances of this header in the PR. I've made an attempt at one here. Any thoughts @simopier @loganharbour?

2023-12-05 02:47 UTC, loganharbour commented on src/userobjects/PICStudyBase.C
> +    _v_z_index(registerRayData("v_z")),
Nah - no need to complicate it. I just wanted to make sure it wasn't easy to remove

2023-12-05 02:48 UTC, loganharbour commented on include/raykernels/PICKernelBase.h
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
Fine by me. remove the redundant www.mooseframework.inl.gov -> mooseframework.inl.gov

2023-12-05 02:53 UTC, loganharbour commented on src/raykernels/PICKernelBase.C
> +  ray->setStartingDirection(direction);
The kernel fundamentally as a system is meant for how the rays propagate, while the study handles everything else. If this is a bit brittle, that's fine it just means we need another way to compartmentalize. 

We can easily have other objects be an input to the study to define how the stepping is done. But it should be separate from the propagation part

2023-12-05 03:37 UTC, gsgall commented on src/raykernels/PICKernelBase.C
> +  ray->setStartingDirection(direction);
That sounds good. I have an initial thought of how to implement this.  Let me know what you think about this 

Create a new user object which has the ability to sample fields at the locations of particles or obtain the average value of a field inside the element in which the ray is contained. This object could then be passed as an input to the pic ray study and have the ray study should call a method in which the rules for how to update the particle velocity within the study are defined.

2023-12-05 22:24 UTC, simopier commented on include/raykernels/PICKernelBase.h
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
Sorry, I don't seem to get github notifications. 

Yes, it looks good to me.

2023-12-06 20:03 UTC, gsgall commented on src/raykernels/PICKernelBase.C
> +PICKernelBase::setDirectionAndMaxDistance(const Real dt)
This logic was moved to a new user object which will be passes an input parameter to the RayTracingStudy and supplies the velocity updating logic.

2023-12-08 14:21 UTC, loganharbour requested changes
Design looks good to me. One small design request (the generation part); the rest of the comments are minor

2023-12-08 14:21 UTC, loganharbour commented on include/userobjects/PICStudyBase.h
> +  std::vector<std::shared_ptr<Ray>> & _banked_rays;
Should not have public data members

2023-12-08 14:21 UTC, loganharbour commented on include/userobjects/PICStudyBase.h
> +  const RayDataIndex _v_z_index;
```suggestion
  /// Ray data for storing velocity components
  ///@{
  const RayDataIndex _v_x_index;
  const RayDataIndex _v_y_index;
  const RayDataIndex _v_z_index;
  ///@}
```

When you wrap in `///@{  ...  ///@}`, they show up grouped in doxygen

2023-12-08 14:21 UTC, loganharbour commented on include/userobjects/PICStudyBase.h
> +  const VelocityUpdaterBase & _velocity_updater;
```suggestion
  /// Whether or not we've generated rays yet (restartable)
  bool & _has_generated;

  /// the velocity updater object which we will hold the rules for how our
  /// particles velocities are updated
  const VelocityUpdaterBase & _velocity_updater;
```

We typically comment vars with `///` and methods with `/*`

2023-12-08 14:21 UTC, loganharbour commented on include/userobjects/PICStudyBase.h
> +#include "ClaimRays.h"
```suggestion
```

I think that these are unused

2023-12-08 14:21 UTC, loganharbour commented on include/userobjects/PICStudyBase.h
> +#include "VelocityUpdaterBase.h"
```suggestion

class VelocityUpdaterBase;
```

You can remove this and only "forward declare" it. All the compiler needs to know in this is that it is a class. When you go acutally call methods on this object (in the source file), you include it there. We put forward declarations after an extra newline after the includes.

2023-12-08 14:21 UTC, loganharbour commented on include/userobjects/VelocityUpdaterBase.h
> +  virtual void execute() override {}
```suggestion
  /**
   * Unused methods
   */
  ///@{
  virtual void initialize() override {}
  virtual void finalize() override {}
  virtual void execute() override {}
  ///@}
```

I think that only the final three need to be overriden. The first ones have default, empty implementations. Also fixes the doxygen comment.

2023-12-08 14:21 UTC, loganharbour commented on include/userobjects/VelocityUpdaterBase.h
> +  virtual void updateVelocity(Ray & ray, const Point v, const Real dt) const;
```suggestion
  virtual void updateVelocity(Ray & ray, const Point & v, const Real dt) const;
```

Anything larger than a value should be passed as a reference. 64 bit references are 8 bytes, double precision Points are 8 * 3 = 24 bytes. That is - we save copying 16 bytes by doing this

2023-12-08 14:21 UTC, loganharbour commented on src/userobjects/PICStudyBase.C
> +  if (!_has_generated)
```suggestion
  else
```

2023-12-08 14:21 UTC, loganharbour commented on src/userobjects/VelocityUpdaterBase.C
> +  // max distance is the
is the...

2023-12-08 14:21 UTC, loganharbour commented on test/src/userobjects/TestPICStudyUserDefinedRays.C
> +  PICStudyBase::generateRays();
So that we don't have this call - what about we create a pure virtual method in the base class `void initializeRays()`, that we then override here instead of `generateRays()`. and then call `initializeRays()` in the base `generateRays()`?

2023-12-08 14:21 UTC, loganharbour commented on test/tests/userobjects/simple_stepping/simple_stepping.i
> +  type = RayTracingExodus
There should be also options to output the ray data here - that way we can test the velocity and (zero) weights too

2023-12-08 14:51 UTC, gsgall commented on test/tests/userobjects/simple_stepping/simple_stepping.i
> +  type = RayTracingExodus
Test input has been updated and regolded to include this change.

2023-12-08 14:51 UTC, gsgall commented on src/userobjects/PICStudyBase.C
> +  if (!_has_generated)
This change was made

2023-12-08 15:40 UTC, gsgall commented on include/userobjects/VelocityUpdaterBase.h
> +  virtual void updateVelocity(Ray & ray, const Point v, const Real dt) const;
This change was made

2023-12-08 15:40 UTC, gsgall commented on include/userobjects/VelocityUpdaterBase.h
> +  virtual void execute() override {}
This change was also made

2023-12-08 15:41 UTC, gsgall commented on src/userobjects/VelocityUpdaterBase.C
> +  // max distance is the
The commend was updated to be more complete

2023-12-08 15:42 UTC, gsgall commented on include/userobjects/PICStudyBase.h
> +  std::vector<std::shared_ptr<Ray>> & _banked_rays;
This member variable was made protected.

2023-12-08 18:16 UTC, loganharbour requested changes
Just about done

2023-12-08 18:16 UTC, loganharbour commented on include/userobjects/PICStudyBase.h
> +  virtual void initializeParticles() {}
```suggestion
  virtual void initializeParticles() = 0;
```

This should be a pure virtual. if you need more info on that concept, let me know.

2023-12-08 18:16 UTC, loganharbour commented on src/userobjects/VelocityUpdaterBase.C
> +  if (dim == 3)
<img width="778" alt="Screenshot 2023-12-08 at 12 12 02 PM" src="https://github.com/idaholab/fenix/assets/22062133/45124765-56a9-44e3-8806-af5b7a58c4c9">

If you look at the coverage diff, you'll see that this line isn't covered. With that - we should make this a 3D test

2023-12-08 18:16 UTC, loganharbour commented on include/userobjects/PICStudyBase.h
> +  bool & _has_generated;
Shouldn't this be private?

2023-12-08 18:16 UTC, loganharbour commented on include/userobjects/PICStudyBase.h
> +  std::vector<std::shared_ptr<Ray>> & _banked_rays;
Shouldn't it be private? What derived classes will need to use it? It's not used in a derived class currently.

It's typically better to make things private up front, and then move them to protected if needed.

2023-12-08 18:17 UTC, loganharbour commented on src/userobjects/PICStudyBase.C
> +    initializeParticles();
Just to get it down on paper (this isn't a review request, just an info request). You do _not_ want to use the same velocity setter that we do in reinit here in the init, correct?

2023-12-08 18:34 UTC, gsgall commented on src/userobjects/PICStudyBase.C
> +    initializeParticles();
That is correct. The main particle stepping algorithm we will be using for EM, the Boris algorithm is similar to a leap frog method. This requires the first step of particles to be a half time step and then from there we take full time steps.

2023-12-08 18:38 UTC, gsgall commented on src/userobjects/VelocityUpdaterBase.C
> +  if (dim == 3)
Test has been updated to make it 3D for coverage.

2023-12-08 18:39 UTC, gsgall commented on include/userobjects/PICStudyBase.h
> +  bool & _has_generated;
Yeah you're right. I've updated that to make sure it's private.

2023-12-13 04:22 UTC, loganharbour requested changes

2023-12-13 04:22 UTC, loganharbour commented on src/userobjects/PICStudyBase.C
> +registerMooseObject("FenixApp", PICStudyBase);
Remove this and you should be able to make the init method a pure virtual.

There's no need to make `PICStudyBase` an object that is usable in input. It's an incomplete base class. It doesn't make sense to instantiate it

2023-12-13 04:26 UTC, gsgall commented on src/userobjects/PICStudyBase.C
> +registerMooseObject("FenixApp", PICStudyBase);
Thank you for the guidance! I just pushed that change.

2023-12-13 04:27 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1941319/) on dbcf0b3 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://salamander-dev.hpc.inl.gov/PRs/7/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://salamander-dev.hpc.inl.gov/PRs/7/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format f0530c571ebf64cf20b7c0a15bf607587ccd8e82`

2023-12-13 04:28 UTC, gsgall commented on test/src/userobjects/TestPICStudyUserDefinedRays.C
> +  PICStudyBase::generateRays();
An `initializeParticles()` method was created for the initial particle creation and a `reinitializeParticles()` method was created to support the re use of particles while avoid the call

2023-12-13 04:32 UTC, gsgall commented on include/userobjects/PICStudyBase.h
> +  virtual void initializeParticles() {}
This change was made and the registration of the PICStudyBase was removed in order to accommodate this change.

2023-12-13 19:58 UTC, loganharbour requested changes
Last change! forgot about doco. code is good

2023-12-13 19:58 UTC, loganharbour commented on doc/content/source/userobjects/VelocityUpdaterBase.md
> +However, only the components of the velocity data corrisponding to the dimension of the mesh will be used in the calculation. If the mesh is 2D then only the first 2 components of velocity will be us
```suggestion
However, only the components of the velocity data corrisponding to the dimension of the mesh will be used in the calculation. If the mesh is 2D then only the first 2 components of velocity will be used for this calculation. This calculation is peformed with `VelocityUpdaterBase::updateVelocity`. This function takes an argument of the ray that needs its velocity updated, the new velocity of the ray and a time step to be used for the maximum distance calculation to allow flexibility for particle pushing methods.

!syntax parameters /UserObjects/VelocityUpdaterBase

!syntax inputs /UserObjects/VelocityUpdaterBase

!syntax children /UserObjects/VelocityUpdaterBase
```

Forgot to say this - this auto fills the parameters, example input files, and children objects in the documentation

2023-12-18 15:55 UTC, loganharbour submitted a review, later dismissed

2023-12-18 15:56 UTC, loganharbour commented
@cticenhour looks like your review re: headers is still around. I could just dismiss and merge, but let's not do that :-)

2023-12-18 16:01 UTC, cticenhour requested changes
All test spec requirements need to be in the form "The system shall....". This comes from our NQA auditors for MOOSE, so we should follow the same standard here. That was the only comment I had, so this PR should be ready to go after this gets fixed up!

2023-12-18 16:01 UTC, cticenhour commented on test/tests/userobjects/simple_stepping/tests
> +    requirement = 'PIC Requires the ability to track 3 velocity components but propagate in lower dimensions'
```suggestion
    requirement = 'The system shall be capable of tracking 3 velocity components within the PIC capability while propagating rays in lower dimensions'
```

2023-12-20 15:29 UTC, cticenhour approved these changes

2023-12-20 15:29 UTC, merged