Add MooseDocs documentation generation to SALAMANDER contributing guidelines
idaholab/fenix pull request #8
Opened 2023-12-12 17:58 UTC by cticenhour

This also necessitated the addition of several items in the main webpage config.yml file, mostly from the python modules documentation, in order to give appropriate context to MooseDocs, etc.

Refs #2

2023-12-12 18:04 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1951212/) on 6bc03be wanted to post the following:

View the site [here](https://salamander-dev.hpc.inl.gov/PRs/8/site)

This comment will be updated on new commits.

2023-12-12 18:05 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1951216/) on 6bc03be wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://salamander-dev.hpc.inl.gov/PRs/8/coverage)



This comment will be updated on new commits.

2023-12-12 18:06 UTC, cticenhour commented
@simopier this is passing and ready for review whenever you have time!

2023-12-12 18:07 UTC, cticenhour commented
@gsgall Take a look at the new additions to the page as well. Do these changes functionally make sense to you (and a representative new SALAMANDER developer)?

2023-12-12 18:25 UTC, gsgall reviewed
Looks good to me.  I think this is a really helpful addition to the website

2023-12-12 18:26 UTC, gsgall approved these changes

2023-12-18 16:28 UTC, simopier requested changes
Thank you Casey, this is awesome. I only have a minor suggestion.

2023-12-18 16:28 UTC, simopier commented on doc/content/sqa/contributing.md
> +
```suggestion

Again, make sure to commit these changes using the instructions above before pushing your branch.
```

2023-12-18 16:44 UTC, cticenhour commented on doc/content/sqa/contributing.md
> +## Pushing and submitting FENIX changes
```suggestion
Again, make sure to commit these changes using the instructions above before pushing your branch.

## Pushing and submitting FENIX changes
```

2023-12-18 16:57 UTC, simopier approved these changes
Thank you Casey!

2023-12-18 16:57 UTC, merged